spring.application.name=invoiceGen
spring.data.mongodb.uri=mongodb://localhost:27017/invoiceGen
#jwt.secret=MySuperSecretKeyThatIsVeryLongAndSecure123!
#jwt.expiration=3600000
spring.security.user.name=user
spring.security.user.password=pass
jwt.secretKey=asja23jcowe425ncoiweckjs38aska2n22-3edq0ncojasco