spring.application.name=invoiceGen
spring.data.mongodb.uri=mongodb://localhost:27017/invoiceGen
#jwt.secret=MySuperSecretKeyThatIsVeryLongAndSecure123!
#jwt.expiration=3600000
# security configuration
spring.security.user.name=user
spring.security.user.password=pass
jwt.secretKey=asja23jcowe425ncoiweckjs38aska2n22-3edq0ncojasco
#email configuration
spring.mail.host=smtp.ethereal.email
spring.mail.port=587
spring.mail.username=norma58@ethereal.email
spring.mail.password=xMYutTAsxwRmrHGZ6V
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true